from __future__ import annotations
import pprint
from pathlib import Path

_TEMPLATE = Path(__file__).resolve().parent / "config_template.py"


def _py(value) -> str:
    # Emit a Python literal (None/True, not JSON null/true) so a blank Sheet cell
    # can never poison the generated config with an unimportable token.
    return pprint.pformat(value, indent=4, sort_dicts=False)


def render_config(cfg: dict) -> str:
    template = _TEMPLATE.read_text(encoding="utf-8")
    parts = [
        "# GENERATED by engine/discover.py at runtime. Do not edit by hand.",
        template,
        "",
        "TESTS = " + _py(cfg.get("tests", {})),
        "RUNS = " + _py(cfg.get("runs", {})),
        "DOE_GROUPS = " + _py(cfg.get("doe_groups", [])),
        "",
    ]
    return "\n".join(parts)


def write_config(cfg: dict, out_path: Path) -> None:
    out_path.write_text(render_config(cfg), encoding="utf-8")
